### ISSUE TITLE
Does this work for you?

### ISSUE THREAD

**Issue by jelling** [parazite13/NativeMenuBar#1]
I tried running the `Sample Scene` from the sample project on Windows 11 with Unity 202.3.33f1 and no menu appeared. 

I wouldn't be surprised if Unity broke this somehow. But it would be nice to use native menus.

**Comment by parazite13** [comment]
I don't see any reason why it's not working anymore on Windows 11. Can you confirm that you've tried running it on Windows Standalone x64 build?

**Comment by jelling** [comment]
Does this look right? 
![image](https://github.com/parazite13/NativeMenuBar/assets/1887486/2aaf20c6-7493-4836-aa1f-5ea8186dbc7b)

Fwiw there is another native menu extension in the asset store that reportedly stopped working as well.

**Comment by parazite13** [comment]
I didn't have the opportunity to try this under windows 11 yet. Unfortunately I won't be able to test that before end of August but I'll give it a try a soon as possible.
In the meantime don't you have the opportunity to build it using latest Unity version and to run the build on a "old" windows 10?

PS: I know that there is no other working solution on this asset that's why I've made mine 😅

**Comment by parazite13** [comment]
Just had the opportunity to check on Windows 11 and it's working has expected with both 2021 LTS and 2022 LTS
![image](https://github.com/parazite13/NativeMenuBar/assets/19252817/651830b1-2474-4aa9-bb11-94ca6641a7c3)
![image](https://github.com/parazite13/NativeMenuBar/assets/19252817/d8073210-8433-4668-a8a1-c7f3d1d441e7)

**Comment by parazite13** [comment]
Can you confirm that is issue is still present for you?

**Comment by jelling** [comment]
Sorry the delay and thank you for the follow-up.

The menu bar appears after I do a build-and-run but it is not present when running inside the emulator. Is that to be expected? Perhaps it's not possible to surface windows UI controls when not running directly on windows? 

![image](https://github.com/parazite13/NativeMenuBar/assets/1887486/3f189a25-d272-4d4e-8670-5f12f23af66c)

**Comment by parazite13** [comment]
Ok then yes it is "as expected", I've updated the Readme to specify it.
I might have the time to have a look at it to check if it can be implemented somehow in the Editor

**Comment by jelling** [comment]
Appreciate it if you do.

**Comment by parazite13** [comment]
I've added a partial implementation usable in the Editor if you want to give it a try
